baseURL = "https://zagreushealth.github.io/"
languageCode = 'en-us'
title = 'Zagreus Health'
#theme = "dead-simple"
#theme = "ananke"
#theme = "hugo-blog-awesome"
theme = "diary"
#theme = "nostyleplease"

[[params.socialIcons]]
name = "github"
url = "https://github.com/zagreushealth"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/zagreusrevival"


