baseURL = "https://zagreushealth.github.io/"
languageCode = 'en-us'
title = 'Zagreus Health'
theme = "diary"

[[menu.main]]
url = "/tags"
name = "Tags"
weight = 3
[[menu.main]]
url = "/posts"
name = "Archive"
weight = 1

